[feed latency] Move default cat into Feed @octocats array. Clear array when feed is loaded.
- When the feed hasn't responded yet, swiping produces a NoMethodError


(main)> 2014-03-15 12:24:34.371 Octodex[16094:70b] app_controller.rb:72:in `display_cat:': undefined method `image_url' for nil:NilClass (NoMethodError)
	from app_controller.rb:78:in `random'
	from app_controller.rb:101:in `swipePreviousGesture:'
2014-03-15 12:24:34.385 Octodex[16094:70b] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'app_controller.rb:72:in `display_cat:': undefined method `image_url' for nil:NilClass (NoMethodError)