[bubble-wrap] Use bubble-wrap 1.1.5.
1 (=4c762b) tsnow@PHAEDO.LOCAL ~/dev/octodex-ios> rake --trace
require 'motion/project' is deprecated, please require 'motion/project/template/ios' instead

rake aborted!
undefined local variable or method `configs' for Motion::Project::App:Class
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545/gems/bubble-wrap-1.1.0/lib/bubble-wrap/ext/motion_project_app.rb:14:in `setup_with_bubblewrap'
/Users/tsnow/dev/octodex-ios/Rakefile:9:in `<top (required)>'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `block in load_rakefile'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545/bin/rake:23:in `load'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545/bin/rake:23:in `<main>'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/Users/tsnow/.rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `<main>'